version: "3.9"

services:
  bot_backend:
    restart: unless-stopped
    build:
      context: .
      dockerfile: apps/bot/backend/Dockerfile-test
    volumes:
      - ./reports/backend:/test/apps/bot/backend/build/reports

  auth_backend:
    restart: unless-stopped
    build:
      context: .
      dockerfile: apps/auth/backend/Dockerfile-test
    volumes:
      - ./reports/backend:/test/apps/auth/backend/build/reports

  bot_discord_bot:
    build:
      context: .
      dockerfile: apps/bot/discord-bot/Dockerfile-test
    volumes:
      - ./reports/discord-bot:/test/apps/bot/discord-bot/build/reports
