version: "3.9"

services:
  auth_backend:
    restart: unless-stopped
    build:
      context: .
      dockerfile: apps/auth/backend/Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - shared_redis
      - shared_mongodb
      - shared_rabbitmq
    volumes:
      - ./ssl:/app/ssl
    env_file:
      - ./.env.docker

  auth_frontend:
    restart: unless-stopped
    build:
      context: .
      dockerfile: apps/auth/frontend/Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./.env.docker

  bot_backend:
    restart: unless-stopped
    build:
      context: .
      dockerfile: apps/bot/backend/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - shared_redis
      - shared_mongodb
      - shared_rabbitmq
    volumes:
      - ./storage:/app/storage
    env_file:
      - ./.env.docker

  bot_backend_consumer:
    restart: unless-stopped
    build:
      context: .
      dockerfile: apps/bot/backend/Dockerfile
    command: ["java", "-jar", "backend.jar", "--consumer"]
    depends_on:
      - shared_redis
      - shared_mongodb
      - shared_rabbitmq
    volumes:
      - ./storage:/app/storage
    env_file:
      - ./.env.docker

  bot_discord_bot:
    build:
      context: .
      dockerfile: apps/bot/discord-bot/Dockerfile
    restart: unless-stopped
    ports:
      - "8082:8082"
    depends_on:
      - shared_redis
      - shared_mongodb
      - shared_rabbitmq
    volumes:
      - ./storage:/app/storage
    env_file:
      - ./.env.docker

  bot_frontend:
    restart: unless-stopped
    build:
      context: .
      dockerfile: apps/bot/frontend/Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - ./.env.docker

  shared_mongodb:
    image: mongo:4.2.22
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db
    env_file:
      - ./.env.infrastructure

  shared_redis:
    image: redis:7.0.4
    restart: unless-stopped
    ports:
      - "6379:6379"

  shared_rabbitmq:
    image: rabbitmq:3.12.0-management-alpine
    restart: unless-stopped
    ports:
      - "8000:15672"
      - "5672:5672"
    volumes:
      - ./etc/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    env_file:
      - ./.env.infrastructure

volumes:
  mongodb:
