version: "3"

services:
  backend:
    restart: unless-stopped
    build:
      context: backend
      dockerfile: Dockerfile
    depends_on:
      - backend_database

  discord_bot:
    build:
      context: discord-bot
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - backend
      - discord_bot_database
      - discord_bot_cache

  backend_database:
    image: mysql:5.7.39
    restart: unless-stopped
    volumes:
      - backend_database:/var/lib/mysql
    env_file:
      - "./docker/.env.mysql"

  discord_bot_database:
    image: mongo:4.2.22
    restart: unless-stopped
    volumes:
      - discord_bot_database:/data/db
    env_file:
      - "./docker/.env.mongodb"

  discord_bot_cache:
    image: redis:7.0.4
    restart: unless-stopped

volumes:
  backend_database:
  discord_bot_database:
