version: "3"

services:
  backend:
    restart: unless-stopped
    build:
      context: .
      dockerfile: app/backend/Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - "./.env"

  frontend:
    restart: unless-stopped
    build:
      context: app/frontend
      dockerfile: Dockerfile

  discord_bot:
    build:
      context: .
      dockerfile: app/discord-bot/Dockerfile
    restart: unless-stopped
    ports:
      - "8081:8081"
    env_file:
      - "./.env"

  mongodb:
    image: mongo:4.2.22
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db
    env_file:
      - "./.env.mongodb"

  redis:
    image: redis:7.0.4
    restart: unless-stopped
    ports:
      - "6279:6379"

volumes:
  mongodb:
