version: "3.9"

services:
  backend:
    restart: unless-stopped
    build:
      context: .
      dockerfile: apps/bot/backend/Dockerfile-test
    volumes:
      - ./reports/backend:/test/apps/bot/backend/build/reports

  discord_bot:
    build:
      context: .
      dockerfile: apps/bot/discord-bot/Dockerfile-test
    volumes:
      - ./reports/discord-bot:/test/apps/bot/discord-bot/build/reports
