version: "3"

services:
  backend:
    restart: unless-stopped
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "1337:1337"
    depends_on:
      - backend_database
    environment:
      DATABASE_HOST: backend_database
      DATABASE_PORT: 3306
      DATABASE_NAME: pekora_backend
      DATABASE_USERNAME: pekora_backend_usr
      DATABASE_PASSWORD: pekora_backend_pw

#  discord_bot:
#    build:
#      context: discord-bot
#      dockerfile: Dockerfile
#    restart: unless-stopped
#    ports:
#      - "3000:3000"

  backend_database:
    image: mysql:5.7.39
    restart: unless-stopped
    volumes:
      - backend_database:/var/lib/mysql
    environment:
      MYSQL_DATABASE: pekora_backend
      MYSQL_USER: pekora_backend_usr
      MYSQL_PASSWORD: pekora_backend_pw
      MYSQL_ROOT_PASSWORD: root

volumes:
  backend_database: