version: "3"

services:
  backend:
    restart: unless-stopped
    build:
      context: .
      dockerfile: app/backend/Dockerfile
    depends_on:
      - backend_database
    env_file:
      - "./.env"

  frontend:
    restart: unless-stopped
    build:
      context: app/frontend
      dockerfile: Dockerfile

  discord_bot:
    build:
      context: .
      dockerfile: app/discord-bot/Dockerfile
    restart: unless-stopped
    depends_on:
      - discord_bot_database
      - discord_bot_cache
    env_file:
      - "./.env"

  backend_database:
    image: mysql:5.7.39
    restart: unless-stopped
    volumes:
      - backend_database:/var/lib/mysql
    env_file:
      - "./docker/.env.mysql"

  discord_bot_database:
    image: mongo:4.2.22
    restart: unless-stopped
    volumes:
      - discord_bot_database:/data/db
    env_file:
      - "./docker/.env.mongodb"

  discord_bot_cache:
    image: redis:7.0.4
    restart: unless-stopped

volumes:
  backend_database:
  discord_bot_database:
