FROM gradle:8.3.0-jdk17-alpine AS build

VOLUME "/test/.gradle"
WORKDIR /test

RUN apk update && \
    apk add zip msmtp mutt curl

COPY . .

RUN gradle clean :apps:bot:backend:build --no-daemon -x test
RUN chmod +x apps/bot/backend/test-entrypoint.sh

ENTRYPOINT ["apps/bot/backend/test-entrypoint.sh"]
