FROM gradle:8.3.0-jdk17-alpine AS build

VOLUME "/test/.gradle"
WORKDIR /test

RUN apk upgrade --update-cache --available && \
    apk add openssl zip msmtp mutt curl && \
    rm -rf /var/cache/apk/*

COPY . .

RUN gradle clean :apps:auth:backend:build --no-daemon -x test && chmod +x apps/auth/backend/entrypoint.sh
RUN chmod +x apps/auth/backend/test-entrypoint.sh

ENTRYPOINT ["apps/auth/backend/test-entrypoint.sh"]
