FROM gradle:7.5.0-jdk17-alpine AS build

VOLUME "/test/.gradle"
WORKDIR /test

COPY . .

RUN apk upgrade --update-cache --available && \
    apk add openssl && \
    rm -rf /var/cache/apk/*

RUN gradle clean :apps:auth:backend:build --no-daemon -x test && chmod +x apps/auth/backend/entrypoint.sh

ENTRYPOINT ["apps/auth/backend/entrypoint.sh"]
