/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package es.magonxesp.pekorabot

import es.magonxesp.pekorabot.discord.startDiscordBot
import kotlin.concurrent.thread

fun main() {
    thread(start = true) {
        startDiscordBot()
    }
}
