/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package es.magonxesp.pekorabot

import es.magonxesp.pekorabot.discord.startDiscordBot
import es.magonxesp.pekorabot.http.startHttpServer

fun main() {
    enableDependencyInjection()

    startDiscordBot()
    startHttpServer()
}
