/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.usadapekora

import com.usadapekora.discord.startDiscordBot
import com.usadapekora.http.startHttpServer
import io.prometheus.client.hotspot.DefaultExports
import com.usadapekora.context.enableDependencyInjection

fun main() {
    enableDependencyInjection()
    DefaultExports.initialize()

    startDiscordBot()
    startHttpServer()
}
